/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.mydsl.services.MyDslGrammarAccess
import patterns.Scenario
import patterns.SimpleMissions

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(Scenario scenario, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (location : scenario.location) {
			location.format
		}
		for (action : scenario.action) {
			action.format
		}
		for (robots : scenario.robots) {
			robots.format
		}
		for (condition : scenario.condition) {
			condition.format
		}
		for (missions : scenario.missions) {
			missions.format
		}
		for (elementaryQuantitativePatterns : scenario.elementaryQuantitativePatterns) {
			elementaryQuantitativePatterns.format
		}
		for (compositePatterns : scenario.compositePatterns) {
			compositePatterns.format
		}
	}

	def dispatch void format(SimpleMissions simpleMissions, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (specificationPatterns : simpleMissions.movementPatterns) {
			specificationPatterns.format
		}
	}
	
	// TODO: implement for ComplexMissions, Negation, Composition, Until, After, Wait, Instantly, Delayed, Promptly, Maximize, Minimize, LessThan, GreaterThan, AtMost, AtLeast, Within, StrictlyWithin, Conservation, Preservation, Repeat, RepeatEvery, Maintain, AbortIf, ResumeIf, Equidistance, Follow, Pause, Timeout, WithConfidence, AlmostAt, ExactlyAt, DeadlineAt, Proportionality
}
